version: "3.5"

services:
  composer:
    image: prooph/composer:7.4
    volumes:
      - .:/app
  web:
    image: bref/fpm-dev-gateway
    ports:
      - '8080:80'
    volumes:
      - .:/var/task
    depends_on:
      - php
      - dynamo
    environment:
      HANDLER: index.php
  php:
    image: bref/php-74-fpm-dev
    volumes:
      - .:/var/task:ro
    env_file:
      - .env.development.local
    expose:
      - 9003
  test:
    image: webdevops/php-dev:7.4
    volumes:
      - .:/app
  dynamo:
    build: docker/dynamo
    environment:
      - TZ=Europe/London
    restart: on-failure
